/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import Processor.conversion;
import Processor.imageProcessor;
import constants.Kernels;
import constants.fixedFilters;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

public class main_view extends javax.swing.JPanel {
    private conversion imageConv = new conversion();
    private String path_string=  "C:/Users/Andy/Desktop/Portfolio resources/view1.jpg";
    public File images_path = new File(path_string);
    public BufferedImage image;
    public ArrayList<Kernels> kernels = new ArrayList<Kernels>();
    imageProcessor ip = new imageProcessor();
    
    public main_view() {
        initComponents();
        try {
            this.image = this.imageConv.conv_StringPathToBufferedImage(this.path_string);
            ImageIcon temp = this.imageConv.conv_BufferedImageToImageIcon(this.image);
            this.original_image.setIcon(temp);
            this.convolved_image.setIcon(temp);
        } catch (IOException ex) {
            Logger.getLogger(main_view.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.init_kernels();
        this.init_combobox();
    }
    private void init_kernels() {
        this.kernels.add(new Kernels("Blur 3x3", fixedFilters.BLUR_3_x_3));
        this.kernels.add(new Kernels("Blur 5x5", fixedFilters.BLUR_5_x_5));
        this.kernels.add(new Kernels("Sharpen", fixedFilters.SHARPEN));
        this.kernels.add(new Kernels("Prewitt Horizontal", fixedFilters.EDGE_LINEAR_HORIZONTAL_PREWITT));
        this.kernels.add(new Kernels("Prewitt Vertical", fixedFilters.EDGE_LINEAR_VERTICAL_PREWITT));
        this.kernels.add(new Kernels("Custom", fixedFilters.CUSTOM_FILTER));   
    }
    private void init_combobox() {
        this.cbox_kernels.removeAllItems();
        for (int i = 0; i<this.kernels.size(); i++) {
            this.cbox_kernels.addItem(this.kernels.get(i).toString());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        convolved_image = new javax.swing.JLabel();
        original_image = new javax.swing.JLabel();
        panel_controller = new javax.swing.JPanel();
        lbl_controller = new javax.swing.JLabel();
        cbox_kernels = new javax.swing.JComboBox();
        lbl_kernels = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tf_file_path = new javax.swing.JTextField();
        bt_browse = new javax.swing.JButton();
        bt_run = new javax.swing.JButton();

        convolved_image.setText("convolved_image");

        original_image.setText("original_image");

        lbl_controller.setText("Controller");

        cbox_kernels.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbl_kernels.setText("Fixed Kernels");

        jLabel1.setText("Input Image");

        bt_browse.setText("Browse");
        bt_browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_browseActionPerformed(evt);
            }
        });

        bt_run.setText("Run");
        bt_run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_runActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_controllerLayout = new javax.swing.GroupLayout(panel_controller);
        panel_controller.setLayout(panel_controllerLayout);
        panel_controllerLayout.setHorizontalGroup(
            panel_controllerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_controllerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_controllerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_controller)
                    .addComponent(cbox_kernels, 0, 171, Short.MAX_VALUE)
                    .addComponent(lbl_kernels)
                    .addComponent(jLabel1)
                    .addComponent(tf_file_path))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_controllerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_browse)
                    .addComponent(bt_run))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panel_controllerLayout.setVerticalGroup(
            panel_controllerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_controllerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_controller)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_controllerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_file_path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_browse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_kernels)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_controllerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbox_kernels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_run))
                .addContainerGap(172, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_controller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(original_image)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(convolved_image)
                .addContainerGap(372, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(convolved_image)
                        .addComponent(original_image))
                    .addComponent(panel_controller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_browseActionPerformed
        //System.out.print(nama);
        JFileChooser chooser = new JFileChooser();
        chooser.setMultiSelectionEnabled(true);
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        chooser.addChoosableFileFilter(new FileNameExtensionFilter("Image File (*.jpg)", "jpg"));
        chooser.setAcceptAllFileFilterUsed(true);
        int result = chooser.showOpenDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION) {
            this.path_string = chooser.getSelectedFile().getAbsolutePath();
            this.tf_file_path.setText(this.path_string);
        }
        try {
            this.image = this.imageConv.conv_StringPathToBufferedImage(this.path_string);
            ImageIcon temp = this.imageConv.conv_BufferedImageToImageIcon(this.image);
            this.original_image.setIcon(temp);
            this.convolved_image.setIcon(temp);
        } catch (IOException ex) {
            Logger.getLogger(main_view.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_bt_browseActionPerformed

    private void bt_runActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_runActionPerformed
        
        File input = new File(this.path_string);
        ArrayList<ArrayList<Double>> display_image_prewit_h = ip.getPixelArrayList(image);
        Kernels selected_kernels = this.kernels.get(this.cbox_kernels.getSelectedIndex());
        display_image_prewit_h = ip.Convolve(display_image_prewit_h, selected_kernels.getKernels());
        BufferedImage image_after = ip.convertMatToBM(display_image_prewit_h);
        ImageIcon temp = new ImageIcon(image_after);
        this.convolved_image.setIcon(temp);
    }//GEN-LAST:event_bt_runActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_browse;
    private javax.swing.JButton bt_run;
    private javax.swing.JComboBox cbox_kernels;
    private javax.swing.JLabel convolved_image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_controller;
    private javax.swing.JLabel lbl_kernels;
    private javax.swing.JLabel original_image;
    private javax.swing.JPanel panel_controller;
    private javax.swing.JTextField tf_file_path;
    // End of variables declaration//GEN-END:variables
}
